### ISSUE TITLE
Edit pgm1.py

### ISSUE THREAD

**Issue by Suman-Banakar** [Suman-Banakar/Embeded-Linux-lab-test#1]
fix code errors, please

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**Following Worker have applied to start work .**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> has been approved to work.**

**Message:** I am starting work on this



<hr>

**This issue has a bounty of $50.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/edit-pgm1py).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help) or the [GitCommits Slack](https://sandbox.app.gitcommits.com/slack)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> has been approved to start work.**

<hr />

**Message:** please go ahead


<a href='https://sandbox.app.gitcommits.com/issue/edit-pgm1py'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** Hi, take this payment


<a href='https://sandbox.app.gitcommits.com/issue/edit-pgm1py'>Click Here to view more</a> on GitCommits Bounty detail page.
