### ISSUE TITLE
add more IPs to ip.txt

### ISSUE THREAD

**Issue by Suman-Banakar** [Suman-Banakar/Embeded-Linux-lab-test#2]

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done**

<hr>

**Following Worker has started work on the bounty. .**

Below user(s) claimed they can complete the work within defined time period.

Please review their action plans below:

**1) <a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> has been approved to work.**

**Message:** I will start work on this ASAP



<hr>

**This issue has a bounty of $100.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt).
- Questions? Checkout [GitCommits Help](https://sandbox.app.gitcommits.com/help) or the [GitCommits Slack](https://sandbox.app.gitcommits.com/slack)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a>, has started work on the bounty.**
<hr />

**Message:** I will start work on this ASAP


<a href='https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by Test1-sap** [comment]
open this

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a> asked <a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> to stop the work on bounty <a href='https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt'>add more IPs to ip.txt</a>.**
<hr />

**Message:** Please stop working on this


<a href='https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a>, You have been requested to restart the work.**
<hr/>

**Funder Message:** Please start work again


<a href='https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**Work has been submitted by <a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a>.**
<hr />

**Message:** please complete payment


<a href='https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/contrib1'>contrib1</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** thank you


<a href='https://sandbox.app.gitcommits.com/issue/add-more-ips-to-iptxt'>Click Here to view more</a> on GitCommits Bounty detail page.
